############################################
# WoDone
# frontend/dockerfile
# Authors: Tobias Höpp
# 
# Dockerfile für wodone_frontend
# Der Docker-Container liefert das Frontend aus
# und dient als reverse proxy für wodone_flask
############################################

# Frontend in eigenem nodejs-Container kompillieren
FROM node:lts-bullseye AS compile-node

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /buildfolder
ADD frontend /buildfolder 
WORKDIR /buildfolder
RUN npm install
RUN npm run build

# Nginx-container nutzen, um Frontend auszuliefern
FROM nginx:stable-alpine

COPY --from=compile-node /buildfolder/www/ /usr/share/nginx/html/
COPY ./default.conf /etc/nginx/conf.d/