version: "3"

services:
    database:
        image: mariadb
        container_name: wodone_database
        restart: always
        volumes:
            - database:/var/lib/mysql
        env_file:
            - ./environment.env
        networks:
            - wodone_database_net

    # api:
    #     build: backend/
    #     container_name: wodone_backend
    #     links:
    #         - database
    #     restart: always
    #     ports:
    #         - 127.0.0.1:8081:80
    #     env_file:
    #         - ./environment.env
    #     volumes:
    #         - wodone_images:/var/www/html/images
    #     networks:
    #         - wodone
    #         - wodone_database_net
    #     deploy:
    #         resources:
    #             reservations:
    #                 devices:
    #                     - driver: nvidia
    #                       count: all
    #                       capabilities: [gpu]

    flask:
        build:
            context: backend/
            dockerfile: dockerfile-flask
        container_name: wodone_flask
        links:
            - database
        restart: always
        ports:
            - 127.0.0.1:8081:80
        env_file:
            - ./environment.env
        volumes:
            - type: volume
              source: wodone_images
              target: /var/www/html/images
              read_only: true
        networks:
            - wodone
            - wodone_database_net

    vqgan:
        build:
            context: backend/
            dockerfile: dockerfile-vqgan
        container_name: wodone_vqgan
        links:
            - database
        restart: always
        env_file:
            - ./environment.env
        volumes:
            - wodone_images:/var/www/html/images
        networks:
            - wodone
            - wodone_database_net
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

    webfrontend:
        build: frontend/
        container_name: wodone_frontend
        restart: always
        ports:
            - 8080:80
        env_file:
            - ./environment.env
        networks:
            - wodone

volumes:
    database:
    wodone_images:

networks:
    wodone:
    wodone_database_net:
