############################################
# WoDone
# backend/dockerfile-flask
# Authors: Tobias Höpp
# 
# Dockerfile für wodone_flask 
# Der Docker-Container beinhaltet Python-Flask, um mittels der Datenbank Suchanfragen 
# und Likes von Bildern zu speichern, sowie den Seed zur Generierung zu bestimmen
############################################
FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND noninteractive

ENV VERSION "1"

USER root

RUN apt-get update && apt-get install -y --no-install-recommends nginx mariadb-client python3 python3-pip uwsgi uwsgi-plugin-python3

COPY python-requirements-flask.txt /tmp

RUN pip3 install -r /tmp/python-requirements-flask.txt

RUN mkdir /usr/local/bin/api
COPY backend /usr/local/bin/api

COPY default /etc/nginx/sites-enabled/

COPY entrypoint-flask.sh /
RUN chmod +x /entrypoint-flask.sh

CMD ["./entrypoint-flask.sh"]
