FROM nvcr.io/nvidia/pytorch:22.01-py3

ENV DEBIAN_FRONTEND noninteractive

ENV VERSION "1"

USER root

RUN apt-get update && apt-get install -y --no-install-recommends nginx mariadb-client python3 python3-pip uwsgi uwsgi-plugin-python3

COPY python-requirements.txt /tmp

RUN pip3 install -r /tmp/python-requirements.txt

#RUN rm -r /etc/nginx/sites-enabled/*

RUN mkdir /usr/local/bin/api
RUN mkdir /usr/local/bin/api/vqgan
RUN cd /usr/local/bin/api/vqgan && \ 
	git clone https://github.com/openai/CLIP && \
	#git clone https://github.com/CompVis/taming-transformers.git taming_transformers && \
	curl -L -o vqgan_imagenet_f16_16384.ckpt -C - 'https://heibox.uni-heidelberg.de/f/867b05fc8c4841768640/?dl=1' && \
	curl -L -o vqgan_imagenet_f16_16384.yaml -C - 'https://heibox.uni-heidelberg.de/f/274fb24ed38341bfa753/?dl=1'


COPY backend /usr/local/bin/api

COPY default /etc/nginx/sites-enabled/
COPY backend/vqgan/000_sample.png /var/www/html/images/

COPY entrypoint.sh /workspace/
RUN chmod +x /workspace/entrypoint.sh

CMD ["./entrypoint.sh"]